create table ORDER_FOOD
(
    FOOD_COUNT    NUMBER not null,
    TABLE_ID      NUMBER not null,
    RESTAURANT_ID NUMBER not null,
    FOOD_ID       NUMBER not null
        constraint ORDER_FOOD_FK1
            references FOOD,
    constraint ORDER_FOOD_PK
        primary key (TABLE_ID, FOOD_ID),
    constraint ORDER_FOOD_FK2
        foreign key (TABLE_ID, RESTAURANT_ID) references TTABLE
)
/

INSERT INTO WRZECOND.ORDER_FOOD (FOOD_COUNT, TABLE_ID, RESTAURANT_ID, FOOD_ID) VALUES (1, 2, 1, 4);
INSERT INTO WRZECOND.ORDER_FOOD (FOOD_COUNT, TABLE_ID, RESTAURANT_ID, FOOD_ID) VALUES (3, 3, 1, 2);
INSERT INTO WRZECOND.ORDER_FOOD (FOOD_COUNT, TABLE_ID, RESTAURANT_ID, FOOD_ID) VALUES (2, 3, 1, 10);
INSERT INTO WRZECOND.ORDER_FOOD (FOOD_COUNT, TABLE_ID, RESTAURANT_ID, FOOD_ID) VALUES (1, 3, 1, 5);
INSERT INTO WRZECOND.ORDER_FOOD (FOOD_COUNT, TABLE_ID, RESTAURANT_ID, FOOD_ID) VALUES (1, 4, 1, 8);
INSERT INTO WRZECOND.ORDER_FOOD (FOOD_COUNT, TABLE_ID, RESTAURANT_ID, FOOD_ID) VALUES (3, 5, 1, 7);
INSERT INTO WRZECOND.ORDER_FOOD (FOOD_COUNT, TABLE_ID, RESTAURANT_ID, FOOD_ID) VALUES (2, 6, 2, 10);
INSERT INTO WRZECOND.ORDER_FOOD (FOOD_COUNT, TABLE_ID, RESTAURANT_ID, FOOD_ID) VALUES (2, 6, 2, 2);
INSERT INTO WRZECOND.ORDER_FOOD (FOOD_COUNT, TABLE_ID, RESTAURANT_ID, FOOD_ID) VALUES (3, 8, 2, 8);
INSERT INTO WRZECOND.ORDER_FOOD (FOOD_COUNT, TABLE_ID, RESTAURANT_ID, FOOD_ID) VALUES (1, 8, 2, 4);
INSERT INTO WRZECOND.ORDER_FOOD (FOOD_COUNT, TABLE_ID, RESTAURANT_ID, FOOD_ID) VALUES (2, 10, 3, 2);
INSERT INTO WRZECOND.ORDER_FOOD (FOOD_COUNT, TABLE_ID, RESTAURANT_ID, FOOD_ID) VALUES (3, 10, 3, 9);
INSERT INTO WRZECOND.ORDER_FOOD (FOOD_COUNT, TABLE_ID, RESTAURANT_ID, FOOD_ID) VALUES (1, 11, 3, 10);
INSERT INTO WRZECOND.ORDER_FOOD (FOOD_COUNT, TABLE_ID, RESTAURANT_ID, FOOD_ID) VALUES (3, 11, 3, 7);
INSERT INTO WRZECOND.ORDER_FOOD (FOOD_COUNT, TABLE_ID, RESTAURANT_ID, FOOD_ID) VALUES (3, 11, 3, 8);
INSERT INTO WRZECOND.ORDER_FOOD (FOOD_COUNT, TABLE_ID, RESTAURANT_ID, FOOD_ID) VALUES (3, 12, 3, 9);
INSERT INTO WRZECOND.ORDER_FOOD (FOOD_COUNT, TABLE_ID, RESTAURANT_ID, FOOD_ID) VALUES (2, 13, 4, 1);
INSERT INTO WRZECOND.ORDER_FOOD (FOOD_COUNT, TABLE_ID, RESTAURANT_ID, FOOD_ID) VALUES (4, 14, 4, 10);
INSERT INTO WRZECOND.ORDER_FOOD (FOOD_COUNT, TABLE_ID, RESTAURANT_ID, FOOD_ID) VALUES (2, 16, 4, 5);
INSERT INTO WRZECOND.ORDER_FOOD (FOOD_COUNT, TABLE_ID, RESTAURANT_ID, FOOD_ID) VALUES (3, 16, 4, 10);
INSERT INTO WRZECOND.ORDER_FOOD (FOOD_COUNT, TABLE_ID, RESTAURANT_ID, FOOD_ID) VALUES (2, 18, 4, 10);
INSERT INTO WRZECOND.ORDER_FOOD (FOOD_COUNT, TABLE_ID, RESTAURANT_ID, FOOD_ID) VALUES (2, 18, 4, 2);
INSERT INTO WRZECOND.ORDER_FOOD (FOOD_COUNT, TABLE_ID, RESTAURANT_ID, FOOD_ID) VALUES (3, 18, 4, 7);
INSERT INTO WRZECOND.ORDER_FOOD (FOOD_COUNT, TABLE_ID, RESTAURANT_ID, FOOD_ID) VALUES (2, 19, 5, 1);
INSERT INTO WRZECOND.ORDER_FOOD (FOOD_COUNT, TABLE_ID, RESTAURANT_ID, FOOD_ID) VALUES (1, 19, 5, 2);
INSERT INTO WRZECOND.ORDER_FOOD (FOOD_COUNT, TABLE_ID, RESTAURANT_ID, FOOD_ID) VALUES (2, 19, 5, 3);
INSERT INTO WRZECOND.ORDER_FOOD (FOOD_COUNT, TABLE_ID, RESTAURANT_ID, FOOD_ID) VALUES (3, 19, 5, 4);
INSERT INTO WRZECOND.ORDER_FOOD (FOOD_COUNT, TABLE_ID, RESTAURANT_ID, FOOD_ID) VALUES (4, 19, 5, 5);
INSERT INTO WRZECOND.ORDER_FOOD (FOOD_COUNT, TABLE_ID, RESTAURANT_ID, FOOD_ID) VALUES (2, 19, 5, 6);
INSERT INTO WRZECOND.ORDER_FOOD (FOOD_COUNT, TABLE_ID, RESTAURANT_ID, FOOD_ID) VALUES (3, 19, 5, 7);
INSERT INTO WRZECOND.ORDER_FOOD (FOOD_COUNT, TABLE_ID, RESTAURANT_ID, FOOD_ID) VALUES (2, 19, 5, 8);
INSERT INTO WRZECOND.ORDER_FOOD (FOOD_COUNT, TABLE_ID, RESTAURANT_ID, FOOD_ID) VALUES (1, 19, 5, 9);
INSERT INTO WRZECOND.ORDER_FOOD (FOOD_COUNT, TABLE_ID, RESTAURANT_ID, FOOD_ID) VALUES (1, 19, 5, 10);
INSERT INTO WRZECOND.ORDER_FOOD (FOOD_COUNT, TABLE_ID, RESTAURANT_ID, FOOD_ID) VALUES (2, 20, 5, 8);
INSERT INTO WRZECOND.ORDER_FOOD (FOOD_COUNT, TABLE_ID, RESTAURANT_ID, FOOD_ID) VALUES (3, 24, 5, 1);
INSERT INTO WRZECOND.ORDER_FOOD (FOOD_COUNT, TABLE_ID, RESTAURANT_ID, FOOD_ID) VALUES (5, 24, 5, 2);
INSERT INTO WRZECOND.ORDER_FOOD (FOOD_COUNT, TABLE_ID, RESTAURANT_ID, FOOD_ID) VALUES (1, 24, 5, 3);
INSERT INTO WRZECOND.ORDER_FOOD (FOOD_COUNT, TABLE_ID, RESTAURANT_ID, FOOD_ID) VALUES (2, 24, 5, 4);
INSERT INTO WRZECOND.ORDER_FOOD (FOOD_COUNT, TABLE_ID, RESTAURANT_ID, FOOD_ID) VALUES (2, 24, 5, 5);
INSERT INTO WRZECOND.ORDER_FOOD (FOOD_COUNT, TABLE_ID, RESTAURANT_ID, FOOD_ID) VALUES (1, 24, 5, 6);
INSERT INTO WRZECOND.ORDER_FOOD (FOOD_COUNT, TABLE_ID, RESTAURANT_ID, FOOD_ID) VALUES (3, 24, 5, 7);
INSERT INTO WRZECOND.ORDER_FOOD (FOOD_COUNT, TABLE_ID, RESTAURANT_ID, FOOD_ID) VALUES (1, 24, 5, 8);
INSERT INTO WRZECOND.ORDER_FOOD (FOOD_COUNT, TABLE_ID, RESTAURANT_ID, FOOD_ID) VALUES (3, 24, 5, 9);
INSERT INTO WRZECOND.ORDER_FOOD (FOOD_COUNT, TABLE_ID, RESTAURANT_ID, FOOD_ID) VALUES (2, 24, 5, 10);
INSERT INTO WRZECOND.ORDER_FOOD (FOOD_COUNT, TABLE_ID, RESTAURANT_ID, FOOD_ID) VALUES (3, 25, 5, 8);
INSERT INTO WRZECOND.ORDER_FOOD (FOOD_COUNT, TABLE_ID, RESTAURANT_ID, FOOD_ID) VALUES (1, 25, 5, 10);
INSERT INTO WRZECOND.ORDER_FOOD (FOOD_COUNT, TABLE_ID, RESTAURANT_ID, FOOD_ID) VALUES (3, 26, 5, 2);
INSERT INTO WRZECOND.ORDER_FOOD (FOOD_COUNT, TABLE_ID, RESTAURANT_ID, FOOD_ID) VALUES (2, 26, 5, 4);
INSERT INTO WRZECOND.ORDER_FOOD (FOOD_COUNT, TABLE_ID, RESTAURANT_ID, FOOD_ID) VALUES (1, 27, 6, 5);
INSERT INTO WRZECOND.ORDER_FOOD (FOOD_COUNT, TABLE_ID, RESTAURANT_ID, FOOD_ID) VALUES (1, 28, 6, 1);
INSERT INTO WRZECOND.ORDER_FOOD (FOOD_COUNT, TABLE_ID, RESTAURANT_ID, FOOD_ID) VALUES (1, 29, 6, 9);