create table RESTAURANT
(
    ID         NUMBER        not null
        constraint RESTAURANT_PK
            primary key,
    NAME       VARCHAR2(64)  not null,
    LOCATION   VARCHAR2(255) not null,
    OPEN_FROM  VARCHAR2(8)   not null,
    OPEN_UNTIL VARCHAR2(8)   not null,
    MANAGER_ID NUMBER        not null
        constraint RESTAURANT_FK1
            references MANAGER
)
/

INSERT INTO WRZECOND.RESTAURANT (ID, NAME, LOCATION, OPEN_FROM, OPEN_UNTIL, MANAGER_ID) VALUES (1, 'Ostravská', 'Rottrova 2800/7,  Ostrava', '08:00', '20:00', 1);
INSERT INTO WRZECOND.RESTAURANT (ID, NAME, LOCATION, OPEN_FROM, OPEN_UNTIL, MANAGER_ID) VALUES (2, 'Café Imperial', 'Na Poříčí 1072/15,  Praha', '00:00', '23:59', 1);
INSERT INTO WRZECOND.RESTAURANT (ID, NAME, LOCATION, OPEN_FROM, OPEN_UNTIL, MANAGER_ID) VALUES (3, 'Divinis', 'Týnská 21,  Praha', '12:00', '17:30', 1);
INSERT INTO WRZECOND.RESTAURANT (ID, NAME, LOCATION, OPEN_FROM, OPEN_UNTIL, MANAGER_ID) VALUES (4, 'Harmony', 'Plukovníka Mráze 1182/24,  Praha 15', '11:00', '23:30', 2);
INSERT INTO WRZECOND.RESTAURANT (ID, NAME, LOCATION, OPEN_FROM, OPEN_UNTIL, MANAGER_ID) VALUES (5, 'Síla chuti', 'Sadová 1170,  Česká Třebová', '10:00', '14:00', 2);
INSERT INTO WRZECOND.RESTAURANT (ID, NAME, LOCATION, OPEN_FROM, OPEN_UNTIL, MANAGER_ID) VALUES (6, 'Červené jablko', 'Polská 1201/1,  Olomouc', '09:00', '23:59', 6);
INSERT INTO WRZECOND.RESTAURANT (ID, NAME, LOCATION, OPEN_FROM, OPEN_UNTIL, MANAGER_ID) VALUES (7, 'Melodie', 'Francouzská 112/25,  Františkovy lázně', '11:00', '12:30', 4);
INSERT INTO WRZECOND.RESTAURANT (ID, NAME, LOCATION, OPEN_FROM, OPEN_UNTIL, MANAGER_ID) VALUES (8, 'Pizzerie Verdi', 'Hradební 5440/1,  Jihlava', '18:00', '23:59', 3);
INSERT INTO WRZECOND.RESTAURANT (ID, NAME, LOCATION, OPEN_FROM, OPEN_UNTIL, MANAGER_ID) VALUES (9, 'Pizzerie Maestro', 'Stará cesta 1826,  Vsetín', '10:00', '22:00', 7);
INSERT INTO WRZECOND.RESTAURANT (ID, NAME, LOCATION, OPEN_FROM, OPEN_UNTIL, MANAGER_ID) VALUES (10, 'Aqua patet', 'Bechyňova 2744/8,  Praha', '09:00', '12:00', 5);
INSERT INTO WRZECOND.RESTAURANT (ID, NAME, LOCATION, OPEN_FROM, OPEN_UNTIL, MANAGER_ID) VALUES (11, 'Pizzerie Verdi', 'Českobudějovická 312,  Kaplice', '00:00', '06:00', 8);
INSERT INTO WRZECOND.RESTAURANT (ID, NAME, LOCATION, OPEN_FROM, OPEN_UNTIL, MANAGER_ID) VALUES (12, 'Melodie', 'Hlavní 18,  Šanov', '12:00', '18:00', 8);