create table INGREDIENT
(
    ID      NUMBER       not null
        constraint INGREDIENT_PK
            primary key,
    NAME    VARCHAR2(64) not null
        constraint INGREDIENT_UK1
            unique,
    FAT     NUMBER       not null,
    FIBER   NUMBER       not null,
    PROTEIN NUMBER       not null,
    SUGAR   NUMBER       not null
)
/

INSERT INTO WRZECOND.INGREDIENT (ID, NAME, FAT, FIBER, PROTEIN, SUGAR) VALUES (1, 'voda', 0, 0, 0, 0);
INSERT INTO WRZECOND.INGREDIENT (ID, NAME, FAT, FIBER, PROTEIN, SUGAR) VALUES (2, 'domácí nudle', 2, 0, 15, 73);
INSERT INTO WRZECOND.INGREDIENT (ID, NAME, FAT, FIBER, PROTEIN, SUGAR) VALUES (3, 'játrový knedlíček', 15, 1, 12, 13);
INSERT INTO WRZECOND.INGREDIENT (ID, NAME, FAT, FIBER, PROTEIN, SUGAR) VALUES (4, 'česnek', 0, 2, 6, 25);
INSERT INTO WRZECOND.INGREDIENT (ID, NAME, FAT, FIBER, PROTEIN, SUGAR) VALUES (5, 'celestýnské nudle', 3, 0, 7, 3);
INSERT INTO WRZECOND.INGREDIENT (ID, NAME, FAT, FIBER, PROTEIN, SUGAR) VALUES (6, 'hrášek', 0, 0, 5, 11);
INSERT INTO WRZECOND.INGREDIENT (ID, NAME, FAT, FIBER, PROTEIN, SUGAR) VALUES (7, 'chléb', 1, 4, 8, 45);
INSERT INTO WRZECOND.INGREDIENT (ID, NAME, FAT, FIBER, PROTEIN, SUGAR) VALUES (8, 'kapr', 12, 0, 18, 1);
INSERT INTO WRZECOND.INGREDIENT (ID, NAME, FAT, FIBER, PROTEIN, SUGAR) VALUES (9, 'niva', 32, 0, 21, 1);
INSERT INTO WRZECOND.INGREDIENT (ID, NAME, FAT, FIBER, PROTEIN, SUGAR) VALUES (10, 'rajčatová omáčka', 6, 1, 2, 8);
INSERT INTO WRZECOND.INGREDIENT (ID, NAME, FAT, FIBER, PROTEIN, SUGAR) VALUES (11, 'masové koule', 17, 0, 7, 12);
INSERT INTO WRZECOND.INGREDIENT (ID, NAME, FAT, FIBER, PROTEIN, SUGAR) VALUES (12, 'houska', 1, 3, 8, 60);
INSERT INTO WRZECOND.INGREDIENT (ID, NAME, FAT, FIBER, PROTEIN, SUGAR) VALUES (13, 'šunka', 6, 0, 18, 2);
INSERT INTO WRZECOND.INGREDIENT (ID, NAME, FAT, FIBER, PROTEIN, SUGAR) VALUES (14, 'sýr', 17, 0, 27, 1);
INSERT INTO WRZECOND.INGREDIENT (ID, NAME, FAT, FIBER, PROTEIN, SUGAR) VALUES (15, 'rajče', 0, 1, 1, 4);
INSERT INTO WRZECOND.INGREDIENT (ID, NAME, FAT, FIBER, PROTEIN, SUGAR) VALUES (16, 'salát', 0, 2, 1, 3);
INSERT INTO WRZECOND.INGREDIENT (ID, NAME, FAT, FIBER, PROTEIN, SUGAR) VALUES (17, 'něco pod tím', 6, 0, 11, 0);
INSERT INTO WRZECOND.INGREDIENT (ID, NAME, FAT, FIBER, PROTEIN, SUGAR) VALUES (18, 'brambory', 0, 2, 1, 16);
INSERT INTO WRZECOND.INGREDIENT (ID, NAME, FAT, FIBER, PROTEIN, SUGAR) VALUES (19, 'rozmarýn', 6, 0, 3, 21);
INSERT INTO WRZECOND.INGREDIENT (ID, NAME, FAT, FIBER, PROTEIN, SUGAR) VALUES (20, 'koňské maso', 7, 0, 21, 1);
INSERT INTO WRZECOND.INGREDIENT (ID, NAME, FAT, FIBER, PROTEIN, SUGAR) VALUES (21, 'hovězí maso', 8, 0, 25, 0);
INSERT INTO WRZECOND.INGREDIENT (ID, NAME, FAT, FIBER, PROTEIN, SUGAR) VALUES (22, 'wasabi', 7, 0, 3, 53);
INSERT INTO WRZECOND.INGREDIENT (ID, NAME, FAT, FIBER, PROTEIN, SUGAR) VALUES (23, 'špenát', 0, 2, 2, 3);