create table MANAGER
(
    ID         NUMBER       not null
        constraint MANAGER_PK
            primary key,
    FIRST_NAME VARCHAR2(64) not null,
    LAST_NAME  VARCHAR2(64) not null
)
/

INSERT INTO WRZECOND.MANAGER (ID, FIRST_NAME, LAST_NAME) VALUES (1, 'Vendelín', 'Bosák');
INSERT INTO WRZECOND.MANAGER (ID, FIRST_NAME, LAST_NAME) VALUES (2, 'Mikuláš', 'Janovský');
INSERT INTO WRZECOND.MANAGER (ID, FIRST_NAME, LAST_NAME) VALUES (3, 'Roman', 'Klusák');
INSERT INTO WRZECOND.MANAGER (ID, FIRST_NAME, LAST_NAME) VALUES (4, 'Gustav', 'Šťastný');
INSERT INTO WRZECOND.MANAGER (ID, FIRST_NAME, LAST_NAME) VALUES (5, 'Bruno', 'Opatrný');
INSERT INTO WRZECOND.MANAGER (ID, FIRST_NAME, LAST_NAME) VALUES (6, 'Hugo', 'Pudil');
INSERT INTO WRZECOND.MANAGER (ID, FIRST_NAME, LAST_NAME) VALUES (7, 'Karel', 'Novák');
INSERT INTO WRZECOND.MANAGER (ID, FIRST_NAME, LAST_NAME) VALUES (8, 'Karel', 'Novák');