-- Odstranění tabulek
--DROP TABLE INGREDIENT_COUNT;
--DROP TABLE FOOD_INGREDIENT;
--DROP TABLE INGREDIENT;
--DROP TABLE ORDER_FOOD;
--DROP TABLE FOOD;
--DROP TABLE CUSTOMER;
--DROP TABLE TTABLE;
--DROP TABLE EMPLOYEE;
--DROP TABLE RESTAURANT;
--DROP TABLE MANAGER;

-- Manažeři restaurací

CREATE TABLE "MANAGER" (	
    "ID" NUMBER NOT NULL ENABLE, 
    "FIRST_NAME" VARCHAR2(64 BYTE) NOT NULL ENABLE, 
    "LAST_NAME" VARCHAR2(64 BYTE) NOT NULL ENABLE,
    
    CONSTRAINT "MANAGER_PK" PRIMARY KEY ("ID")
    USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
    TABLESPACE "USERS"  ENABLE
) SEGMENT CREATION DEFERRED PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING TABLESPACE "USERS";

-- Restaurace

CREATE TABLE "RESTAURANT" (	
    "ID" NUMBER NOT NULL ENABLE, 
    "NAME" VARCHAR2(64 BYTE) NOT NULL ENABLE, 
    "LOCATION" VARCHAR2(255 BYTE) NOT NULL ENABLE, 
    "OPEN_FROM" VARCHAR2(8 BYTE) NOT NULL ENABLE, 
    "OPEN_UNTIL" VARCHAR2(8 BYTE) NOT NULL ENABLE, 
    "MANAGER_ID" NUMBER NOT NULL ENABLE, 
    
    CONSTRAINT "RESTAURANT_PK" PRIMARY KEY ("ID")
    USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
    TABLESPACE "USERS"  ENABLE, 
    
    CONSTRAINT "RESTAURANT_FK1" FOREIGN KEY ("MANAGER_ID")
    REFERENCES "MANAGER" ("ID") ENABLE
) SEGMENT CREATION DEFERRED PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING TABLESPACE "USERS";

-- Zaměstnanci

CREATE TABLE "EMPLOYEE" (
    "ID" NUMBER NOT NULL ENABLE, 
    "COOK" NUMBER NOT NULL ENABLE, 
    "FIRST_NAME" VARCHAR2(64 BYTE) NOT NULL ENABLE, 
    "LAST_NAME" VARCHAR2(64 BYTE) NOT NULL ENABLE, 
    "SALARY" NUMBER NOT NULL ENABLE, 
    "RESTAURANT_ID" NUMBER NOT NULL ENABLE, 

    CONSTRAINT "EMPLOYEE_PK" PRIMARY KEY ("ID")
    USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
    TABLESPACE "USERS"  ENABLE, 

    CONSTRAINT "EMPLOYEE_FK1" FOREIGN KEY ("RESTAURANT_ID")
    REFERENCES "RESTAURANT" ("ID") ENABLE
) SEGMENT CREATION DEFERRED PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING TABLESPACE "USERS";

-- Stoly

CREATE TABLE "TTABLE" (
    "ID" NUMBER NOT NULL ENABLE, 
    "CAPACITY" NUMBER NOT NULL ENABLE, 
    "TYPE" NUMBER NOT NULL ENABLE, 
    "RESTAURANT_ID" NUMBER NOT NULL ENABLE, 
    "WAITER_ID" NUMBER NOT NULL ENABLE, 
    
    CONSTRAINT "TTABLE_PK" PRIMARY KEY ("ID", "RESTAURANT_ID")
    USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
    TABLESPACE "USERS"  ENABLE, 
  
    CONSTRAINT "TTABLE_FK1" FOREIGN KEY ("WAITER_ID")
    REFERENCES "EMPLOYEE" ("ID") ENABLE, 
    
    CONSTRAINT "TTABLE_FK2" FOREIGN KEY ("RESTAURANT_ID")
    REFERENCES "RESTAURANT" ("ID") ENABLE
) SEGMENT CREATION DEFERRED PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING TABLESPACE "USERS";

-- Zákazníci

CREATE TABLE "CUSTOMER" (
    "ID" NUMBER NOT NULL ENABLE, 
    "AGE" NUMBER NOT NULL ENABLE, 
    "FIRST_NAME" VARCHAR2(64 BYTE) NOT NULL ENABLE, 
    "LAST_NAME" VARCHAR2(64 BYTE) NOT NULL ENABLE, 
    "TABLE_ID" NUMBER NOT NULL ENABLE, 
    "RESTAURANT_ID" NUMBER NOT NULL ENABLE, 

    CONSTRAINT "CUSTOMER_PK" PRIMARY KEY ("ID")
    USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
    TABLESPACE "USERS"  ENABLE, 
    
    CONSTRAINT "CUSTOMER_FK1" FOREIGN KEY ("TABLE_ID", "RESTAURANT_ID")
    REFERENCES "TTABLE" ("ID", "RESTAURANT_ID") ENABLE
) SEGMENT CREATION DEFERRED PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING TABLESPACE "USERS";

-- Jídla

CREATE TABLE "FOOD" (
    "ID" NUMBER NOT NULL ENABLE, 
    "NAME" VARCHAR2(128 BYTE) NOT NULL ENABLE, 
    "PRICE" NUMBER NOT NULL ENABLE, 
    
    CONSTRAINT "FOOD_PK" PRIMARY KEY ("ID")
    USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
    TABLESPACE "USERS"  ENABLE, 
    
    CONSTRAINT "FOOD_UK1" UNIQUE ("NAME")
    USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
    TABLESPACE "USERS"  ENABLE
) SEGMENT CREATION DEFERRED PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING TABLESPACE "USERS";

-- Jídla v objednávkách

CREATE TABLE "ORDER_FOOD" (
    "FOOD_COUNT" NUMBER NOT NULL ENABLE, 
    "TABLE_ID" NUMBER NOT NULL ENABLE, 
    "RESTAURANT_ID" NUMBER NOT NULL ENABLE, 
    "FOOD_ID" NUMBER NOT NULL ENABLE, 
    
    CONSTRAINT "ORDER_FOOD_PK" PRIMARY KEY ("TABLE_ID", "FOOD_ID")
    USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
    TABLESPACE "USERS"  ENABLE, 
    
    CONSTRAINT "ORDER_FOOD_FK1" FOREIGN KEY ("FOOD_ID")
    REFERENCES "FOOD" ("ID") ENABLE, 
    
    CONSTRAINT "ORDER_FOOD_FK2" FOREIGN KEY ("TABLE_ID", "RESTAURANT_ID")
    REFERENCES "TTABLE" ("ID", "RESTAURANT_ID") ENABLE
) SEGMENT CREATION DEFERRED PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING TABLESPACE "USERS";

-- Ingredience

CREATE TABLE "INGREDIENT" (
    "ID" NUMBER NOT NULL ENABLE, 
    "NAME" VARCHAR2(64 BYTE) NOT NULL ENABLE, 
    "FAT" NUMBER NOT NULL ENABLE, 
    "FIBER" NUMBER NOT NULL ENABLE, 
    "PROTEIN" NUMBER NOT NULL ENABLE, 
    "SUGAR" NUMBER NOT NULL ENABLE, 
    
    CONSTRAINT "INGREDIENT_PK" PRIMARY KEY ("ID")
    USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
    TABLESPACE "USERS"  ENABLE, 
    
    CONSTRAINT "INGREDIENT_UK1" UNIQUE ("NAME")
    USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
    TABLESPACE "USERS"  ENABLE
) SEGMENT CREATION DEFERRED PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING TABLESPACE "USERS";

-- Potřebné ingredience k daným jídlům

CREATE TABLE "FOOD_INGREDIENT" (
    "INGREDIENT_COUNT" NUMBER NOT NULL ENABLE, 
    "UNIT" VARCHAR2(8 BYTE) NOT NULL ENABLE, 
    "INGREDIENT_ID" NUMBER NOT NULL ENABLE, 
    "FOOD_ID" NUMBER NOT NULL ENABLE, 
    
    CONSTRAINT "FOOD_INGREDIENT_PK" PRIMARY KEY ("INGREDIENT_ID", "FOOD_ID")
    USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
    TABLESPACE "USERS"  ENABLE, 
    
    CONSTRAINT "FOOD_INGREDIENT_FK1" FOREIGN KEY ("INGREDIENT_ID")
    REFERENCES "INGREDIENT" ("ID") ENABLE, 
    
    CONSTRAINT "FOOD_INGREDIENT_FK2" FOREIGN KEY ("FOOD_ID")
    REFERENCES "FOOD" ("ID") ENABLE
) SEGMENT CREATION DEFERRED PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING TABLESPACE "USERS";

-- Stav ingrediencí na skladech

CREATE TABLE "INGREDIENT_COUNT" (
    "INGREDIENT_COUNT" NUMBER NOT NULL ENABLE, 
    "INGREDIENT_ID" NUMBER NOT NULL ENABLE, 
    "RESTAURANT_ID" NUMBER NOT NULL ENABLE, 
    
    CONSTRAINT "INGREDIENT_COUNT_PK" PRIMARY KEY ("INGREDIENT_ID", "RESTAURANT_ID")
    USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
    TABLESPACE "USERS"  ENABLE, 
    
    CONSTRAINT "INGREDIENT_COUNT_FK1" FOREIGN KEY ("INGREDIENT_ID")
    REFERENCES "INGREDIENT" ("ID") ENABLE, 
    
    CONSTRAINT "INGREDIENT_COUNT_FK2" FOREIGN KEY ("RESTAURANT_ID")
    REFERENCES "RESTAURANT" ("ID") ENABLE
) SEGMENT CREATION DEFERRED PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING TABLESPACE "USERS";