-- Odstranění tabulek
DROP TABLE TJV_ORDER_FOOD;
DROP TABLE TJV_ORDER;
DROP TABLE TJV_FOOD;
DROP TABLE TJV_TABLE;
DROP TABLE TJV_EMPLOYEE;

-- Zaměstnanci

CREATE TABLE "TJV_EMPLOYEE" (
    "ID" NUMBER NOT NULL ENABLE,
    "USERNAME" VARCHAR2(16 BYTE) NOT NULL ENABLE,
    "PASSWORD" CLOB NOT NULL ENABLE,
    "FIRST_NAME" VARCHAR2(64 BYTE) NOT NULL ENABLE,
    "LAST_NAME" VARCHAR2(64 BYTE) NOT NULL ENABLE,
    "ADMIN" NUMBER NOT NULL ENABLE,

    CONSTRAINT "TJV_EMPLOYEE_PK" PRIMARY KEY ("ID")
        USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
        TABLESPACE "USERS" ENABLE,

    CONSTRAINT "TJV_EMPLOYEE_UK" UNIQUE ("USERNAME")
        USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
        TABLESPACE "USERS"  ENABLE
) SEGMENT CREATION DEFERRED PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING TABLESPACE "USERS";

-- Stoly

CREATE TABLE "TJV_TABLE" (
    "ID" NUMBER NOT NULL ENABLE,
    "TYPE" NUMBER NOT NULL ENABLE,

    CONSTRAINT "TJV_TABLE_PK" PRIMARY KEY ("ID")
        USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255
        TABLESPACE "USERS"  ENABLE
) SEGMENT CREATION DEFERRED PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING TABLESPACE "USERS";

-- Jídla

CREATE TABLE "TJV_FOOD" (
    "ID" NUMBER NOT NULL ENABLE,
    "NAME" VARCHAR2(128 BYTE) NOT NULL ENABLE,
    "PRICE" NUMBER NOT NULL ENABLE,

    CONSTRAINT "TJV_FOOD_PK" PRIMARY KEY ("ID")
        USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255
        TABLESPACE "USERS"  ENABLE,

    CONSTRAINT "TJV_FOOD_UK" UNIQUE ("NAME")
        USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
        TABLESPACE "USERS"  ENABLE
) SEGMENT CREATION DEFERRED PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING TABLESPACE "USERS";

-- Objednávky

CREATE TABLE "TJV_ORDER" (
    "ID" NUMBER NOT NULL ENABLE,
    "EMPLOYEE_ID" NUMBER NOT NULL ENABLE,
    "TABLE_ID" NUMBER NOT NULL ENABLE,
    "CREATED" TIMESTAMP NOT NULL ENABLE,

    CONSTRAINT "TJV_ORDER_PK" PRIMARY KEY ("ID")
        USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255
        TABLESPACE "USERS"  ENABLE,

    CONSTRAINT "TJV_ORDER_FK1" FOREIGN KEY ("EMPLOYEE_ID")
        REFERENCES "TJV_EMPLOYEE" ("ID") ENABLE,

    CONSTRAINT "TJV_ORDER_FK2" FOREIGN KEY ("TABLE_ID")
        REFERENCES "TJV_TABLE" ("ID") ENABLE
) SEGMENT CREATION DEFERRED PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING TABLESPACE "USERS";


-- Jídla v objednávkách

CREATE TABLE "TJV_ORDER_FOOD" (
    "ORDER_ID" NUMBER NOT NULL ENABLE,
    "FOOD_ID" NUMBER NOT NULL ENABLE,
    "FOOD_COUNT" NUMBER NOT NULL ENABLE,
    "COMPLETED" TIMESTAMP NOT NULL ENABLE,

    CONSTRAINT "TJV_ORDER_FOOD_PK" PRIMARY KEY ("ORDER_ID", "FOOD_ID")
      USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255
      TABLESPACE "USERS"  ENABLE,

    CONSTRAINT "TJV_ORDER_FOOD_FK1" FOREIGN KEY ("ORDER_ID")
        REFERENCES "TJV_ORDER" ("ID") ENABLE,

    CONSTRAINT "TJV_ORDER_FOOD_FK2" FOREIGN KEY ("FOOD_ID")
      REFERENCES "TJV_FOOD" ("ID") ENABLE
) SEGMENT CREATION DEFERRED PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING TABLESPACE "USERS";