# Prefix
PREFIX restaurant: <http://wrzecond.fit.cvut.cz/restaurant/>
PREFIX manager: <http://wrzecond.fit.cvut.cz/manager/>

# 2. Restaurace, jejichž manažer se nejmenuje "Vendelín"

SELECT ?restaurant ?restaurant_id ?restaurant_name (CONCAT(?first_name, " ", ?last_name) AS ?manager_name)
WHERE {
    ?restaurant restaurant:id ?restaurant_id ;
                restaurant:name ?restaurant_name ;
                restaurant:managed_by ?manager .
    ?manager manager:first_name ?first_name ;
             manager:last_name ?last_name .
    FILTER (?first_name != "Vendelín")
}
ORDER BY ?restaurant_id
LIMIT 10