# Prefix
PREFIX food: <http://wrzecond.fit.cvut.cz/food/>
PREFIX food_ingredient: <http://wrzecond.fit.cvut.cz/food/ingredient/>
PREFIX ingredient: <http://wrzecond.fit.cvut.cz/ingredient/>

SELECT DISTINCT ?ingredient ?ingredient_name (SUM(?ingredient_count) AS ?total_count) ?unit
WHERE {
    ?food food:name ?food_name .
    ?food_ingredient food_ingredient:makes ?food ;
                     food_ingredient:unit ?unit ;
                     food_ingredient:count ?ingredient_count ;
                     food_ingredient:with ?ingredient .
    ?ingredient ingredient:name ?ingredient_name
    FILTER (?food_name = "Hovězí vývar s celestýnskými nudlemi" || ?food_name = "Rumcajsovy koule")
}
GROUP BY ?ingredient ?ingredient_name ?unit
ORDER BY DESC(?total_count)
LIMIT 10