security:
    enable_authenticator_manager: true
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'
        App\Entity\Account:
            algorithm: auto
    providers:
        app_user_provider:
            entity:
                class: App\Entity\Account
                property: name
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            lazy: true
            provider: app_user_provider
            custom_authenticator: App\Security\AccountAuthenticator
            logout:
                path: app_logout
                target: app_login
    access_control:
        - { path: ^/api/, roles: PUBLIC_ACCESS }
        - { path: ^/login, roles: PUBLIC_ACCESS }
        - { path: ^/employee/, roles: ROLE_USER }
        - { path: ^/employee, roles: PUBLIC_ACCESS }
        - { path: ^/, roles: ROLE_USER }
