# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/segment7.xdc

# Block Designs: bd/design_1/design_1.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1 || ORIG_REF_NAME==design_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_and_0_0/design_1_and_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_and_0_0 || ORIG_REF_NAME==design_1_and_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_and_1_0/design_1_and_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_and_1_0 || ORIG_REF_NAME==design_1_and_1_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_and_2_0/design_1_and_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_and_2_0 || ORIG_REF_NAME==design_1_and_2_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xor_0_0/design_1_xor_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xor_0_0 || ORIG_REF_NAME==design_1_xor_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_and_0_1/design_1_and_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_and_0_1 || ORIG_REF_NAME==design_1_and_0_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_and_1_1/design_1_and_1_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_and_1_1 || ORIG_REF_NAME==design_1_and_1_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xor_0_1/design_1_xor_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xor_0_1 || ORIG_REF_NAME==design_1_xor_0_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_and_0_2/design_1_and_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_and_0_2 || ORIG_REF_NAME==design_1_and_0_2} -quiet] -quiet

# IP: bd/design_1/ip/design_1_and_0_3/design_1_and_0_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_and_0_3 || ORIG_REF_NAME==design_1_and_0_3} -quiet] -quiet

# IP: bd/design_1/ip/design_1_or_0_0/design_1_or_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_or_0_0 || ORIG_REF_NAME==design_1_or_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_and_0_4/design_1_and_0_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_and_0_4 || ORIG_REF_NAME==design_1_and_0_4} -quiet] -quiet

# IP: bd/design_1/ip/design_1_and_1_2/design_1_and_1_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_and_1_2 || ORIG_REF_NAME==design_1_and_1_2} -quiet] -quiet

# IP: bd/design_1/ip/design_1_and_2_1/design_1_and_2_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_and_2_1 || ORIG_REF_NAME==design_1_and_2_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_or_0_1/design_1_or_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_or_0_1 || ORIG_REF_NAME==design_1_or_0_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_and_0_5/design_1_and_0_5.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_and_0_5 || ORIG_REF_NAME==design_1_and_0_5} -quiet] -quiet

# IP: bd/design_1/ip/design_1_and_1_3/design_1_and_1_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_and_1_3 || ORIG_REF_NAME==design_1_and_1_3} -quiet] -quiet

# IP: bd/design_1/ip/design_1_and_2_2/design_1_and_2_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_and_2_2 || ORIG_REF_NAME==design_1_and_2_2} -quiet] -quiet

# IP: bd/design_1/ip/design_1_and_3_0/design_1_and_3_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_and_3_0 || ORIG_REF_NAME==design_1_and_3_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xor_0_2/design_1_xor_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xor_0_2 || ORIG_REF_NAME==design_1_xor_0_2} -quiet] -quiet

# IP: bd/design_1/ip/design_1_or_0_2/design_1_or_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_or_0_2 || ORIG_REF_NAME==design_1_or_0_2} -quiet] -quiet

# IP: bd/design_1/ip/design_1_and_0_6/design_1_and_0_6.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_and_0_6 || ORIG_REF_NAME==design_1_and_0_6} -quiet] -quiet

# IP: bd/design_1/ip/design_1_and_1_4/design_1_and_1_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_and_1_4 || ORIG_REF_NAME==design_1_and_1_4} -quiet] -quiet

# IP: bd/design_1/ip/design_1_and_2_3/design_1_and_2_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_and_2_3 || ORIG_REF_NAME==design_1_and_2_3} -quiet] -quiet

# IP: bd/design_1/ip/design_1_or_0_3/design_1_or_0_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_or_0_3 || ORIG_REF_NAME==design_1_or_0_3} -quiet] -quiet

# IP: bd/design_1/ip/design_1_and_0_7/design_1_and_0_7.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_and_0_7 || ORIG_REF_NAME==design_1_and_0_7} -quiet] -quiet

# IP: bd/design_1/ip/design_1_and_1_5/design_1_and_1_5.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_and_1_5 || ORIG_REF_NAME==design_1_and_1_5} -quiet] -quiet

# IP: bd/design_1/ip/design_1_and_2_4/design_1_and_2_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_and_2_4 || ORIG_REF_NAME==design_1_and_2_4} -quiet] -quiet

# IP: bd/design_1/ip/design_1_or_0_4/design_1_or_0_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_or_0_4 || ORIG_REF_NAME==design_1_or_0_4} -quiet] -quiet

# IP: bd/design_1/ip/design_1_gnd_0_0/design_1_gnd_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_gnd_0_0 || ORIG_REF_NAME==design_1_gnd_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_vcc_0_0/design_1_vcc_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_vcc_0_0 || ORIG_REF_NAME==design_1_vcc_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_vcc_0_1/design_1_vcc_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_vcc_0_1 || ORIG_REF_NAME==design_1_vcc_0_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_vcc_0_2/design_1_vcc_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_vcc_0_2 || ORIG_REF_NAME==design_1_vcc_0_2} -quiet] -quiet

# IP: bd/design_1/ip/design_1_and_0_8/design_1_and_0_8.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_and_0_8 || ORIG_REF_NAME==design_1_and_0_8} -quiet] -quiet

# IP: bd/design_1/ip/design_1_and_1_6/design_1_and_1_6.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_and_1_6 || ORIG_REF_NAME==design_1_and_1_6} -quiet] -quiet

# IP: bd/design_1/ip/design_1_and_2_5/design_1_and_2_5.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_and_2_5 || ORIG_REF_NAME==design_1_and_2_5} -quiet] -quiet

# IP: bd/design_1/ip/design_1_and_3_1/design_1_and_3_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_and_3_1 || ORIG_REF_NAME==design_1_and_3_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_or_0_5/design_1_or_0_5.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_or_0_5 || ORIG_REF_NAME==design_1_or_0_5} -quiet] -quiet

# XDC: bd/design_1/design_1_ooc.xdc
