# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/gates.xdc

# Block Designs: bd/gates/gates.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==gates || ORIG_REF_NAME==gates} -quiet] -quiet

# IP: bd/gates/ip/gates_and_0_0/gates_and_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==gates_and_0_0 || ORIG_REF_NAME==gates_and_0_0} -quiet] -quiet

# IP: bd/gates/ip/gates_and_1_0/gates_and_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==gates_and_1_0 || ORIG_REF_NAME==gates_and_1_0} -quiet] -quiet

# IP: bd/gates/ip/gates_or_0_0/gates_or_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==gates_or_0_0 || ORIG_REF_NAME==gates_or_0_0} -quiet] -quiet

# IP: bd/gates/ip/gates_xor_0_0/gates_xor_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==gates_xor_0_0 || ORIG_REF_NAME==gates_xor_0_0} -quiet] -quiet

# XDC: bd/gates/gates_ooc.xdc
